### ISSUE TITLE
How to close App from topbar?

### ISSUE THREAD

**Issue by maliknur** [pablopunk/healthi-app#10]
There is no option to close application once it launched.

**Comment by pablopunk** [comment]
@maliknur hmmm you can close it by clicking anywhere outside the window, but maybe it would make sense just to have a little X button

**Comment by maliknur** [comment]
<img width="508" alt="screen shot 2017-02-17 at 3 05 45 pm" src="https://cloud.githubusercontent.com/assets/12554919/23086614/dd2870ca-f522-11e6-81b1-f6335a813317.png">

Sorry, maybe my issue description wasn't clear enough.
I mean when app is launched and its icon appear in topbar, this is no context menu to close/remove it from topbar

**Comment by pablopunk** [comment]
Ohhh okay, you just have to press CMD+Q while the window is open

Pablo P. Varela
via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=9.4.52&pv=10.2.1&source=email_footer_2]
On Sat, Feb 18, 2017 at 12:09 AM, Malik Nur <notifications@github.com> wrote:
[https://cloud.githubusercontent.com/assets/12554919/23086614/dd2870ca-f522-11e6-81b1-f6335a813317.png]

Sorry, maybe my issue description wasn't clear enough.
I mean when app is launched and its icon appear in topbar, this is no context menu to close/remove it from topbar

**Comment by pablopunk** [comment]
Ohh okay, you just have to press CMD+Q while the window is open

**Comment by pablopunk** [comment]
@maliknur I added a close button to make it clear, thanks 🙌
