### ISSUE TITLE
Chrome Dev tools short key binds globally to the tray

### ISSUE THREAD

**Issue by ericadamski** [pablopunk/healthi-app#11]
When I press `cmd+alt+i` for dev tools in chrome, it always opens the dev tools in the tray
![kapture 2017-03-13 at 10 16 52](https://cloud.githubusercontent.com/assets/6516758/23858250/37cc93f6-07d6-11e7-9e01-fed8e46d523a.gif)

**Comment by pablopunk** [comment]
@ericadamski You mean you wanna open the dev tools in Chrome and they open in _healthi_ instead? Try opening them in Chrome with the _healthi_ window hidden.

If you meant you wanna open the _healthi_ dev tools and they are too small to see, try resizing the _healthi_ window 👍

**Comment by ericadamski** [comment]
@pablopunk You probably shouldn't allow me to use dev tools in a production level application, however it still binds when the tray isn't open. If you need me to I can send another GIF 👍 

Thanks for the fast response!!

**Comment by pablopunk** [comment]
@ericadamski oh wait, ok, I know what you mean. I will try to fix it ASAP, thanks ;)

**Comment by pablopunk** [comment]
@ericadamski making a new release to get the last commits, it's fixed ;)

**Comment by ericadamski** [comment]
@pablopunk you da 💣👌👌
