### ISSUE TITLE
Reload window on ⌘+R

### ISSUE THREAD

**Issue by pablopunk** [pablopunk/healthi-app#24]
Allow `⌘+R` to reload the window so you can see the updated battery health

**Comment by V1shvesh** [comment]
Still open? Help needed? Count me in if so!!

**Comment by pablopunk** [comment]
@V1shvesh sure!

**Comment by V1shvesh** [comment]
I'm sorry, but I'm having a hard time trying to understand what exactly I gotta do. Could you point me in the right direction?

**Comment by pablopunk** [comment]
@V1shvesh at first it had a button to refresh the battery status (basically reloading electron window, [as you can see here](https://github.com/pablopunk/healthi-app/blob/23758d01d6110302f83eaf4a0e17b567a263ba40/src/index.js#L87)) but I removed that button cause I want to do that with `Cmd+R`

**Comment by pablopunk** [comment]
Don't really need this. Closing.
