### ISSUE TITLE
△ Change name to `healthi-app` 

### ISSUE THREAD

**Issue by pablopunk** [pablopunk/healthi-app#3]
The name `healthi.app` can cause conflicts in MacOS because if you clone the repo without specifying the output directory, it's gonna create a folder called `healthi.app`, which is interpreted as an actual application.

<img width="240" alt="screen shot 2017-01-09 at 7 46 14 pm" src="https://cloud.githubusercontent.com/assets/4324982/21789612/4e5a67f0-d6a4-11e6-9acd-0919713cf506.png">

## To do

* [x] Change repo name (@pablopunk)
* [x] Change all references in project (`package.json`)
* [x] Rename external links like [electron apps](https://github.com/electron/electron-apps/blob/master/apps/healthi/healthi.yml)

**Comment by takumab** [comment]
Hey, just to clarify, you want the repo name changed to @pablopunk and 'healthi.app' changed to 'healthi-app' in package.json? Also rename the links to ".../healthi-app"?

**Comment by pablopunk** [comment]
@takumab oh I meant that only me (@pablopunk) could change the repo name 😂.

Yeah basically changing `package.json` "name" and urls (like repo, bugs...)

**Comment by takumab** [comment]
Haha. Oh ok. My bad. This is my first go at making a PR. Thanks

**Comment by pablopunk** [comment]
@takumab Awesome, I actually left this here for beginners to start pull requesting 👍

**Comment by takumab** [comment]
Should I create another branch before I make the changes?

**Comment by pablopunk** [comment]
@takumab for small changes like this one is not necessary, master is okay

**Comment by takumab** [comment]
Ok. Cool. Thanks

**Comment by pablopunk** [comment]
Closing with https://github.com/pablopunk/healthi-app/pull/8

**Comment by takumab** [comment]
Thanks for the opportunity.

**Comment by pablopunk** [comment]
@takumab you are very welcome.

[Here is the release!](https://github.com/pablopunk/healthi-app/releases/tag/1.3.0)
